spring:
  application:
    name: spring-openai-demo



  ai:
   openai:
     api-key: ${OPENAI_API_KEY}

#
#
#
#logging:
#  level:
#    org:
#      springframework:
#        ai:
#          chat:
#            client:
#              advisor: DEBUG

server:
  port: 9292